version: '2'
services:
    assignment2-app:
        image: assignment2
        external_links:
            - assignment2-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/assignment2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    assignment2-mysql:
        extends:
            file: mysql.yml
            service: assignment2-mysql
